- name: CMake Konfigürasyonu
      # Komutun sonuna mutlaka bir nokta (.) eklemeliyiz ki CMake kodları nerede bulacağını bilsin
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Projeyi Derle (Build)
      run: cmake --build build --config Release
