name: C++ Anti-Debug Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Repoyu Klonla (Checkout)
      uses: actions/checkout@v3

    - name: CMake Konfigürasyonu
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Projeyi Derle (Build)
      run: cmake --build ${{github.workspace}}/build --config Release
